### ISSUE TITLE
Android Keyboard Handling

### ISSUE THREAD

**Issue by kickbk** [gorhom/react-native-bottom-sheet#509] opened 2021-06-24 16:19 UTC
# Bug

Keyboard handling with Android is a nightmare, so @gorhom I'm grateful for your patience and hard work on this.

Here is a clean example that will highlight the different bugs I am facing.
Please check each point using an iPhone and an Android device to compare.

If I find new bugs, I will update this issue.
Also, when you introduce a new fix, we can use this issue to make sure the bugs are resolved and test to see no other exist.

Everyone else is welcome to comment. If you can suggest a new way to produce a bug with clean code, please share and I will update the snack to demonstrate.

## Environment info

I'm using alpha 12 because I cannot use the https://github.com/gorhom/react-native-bottom-sheet/tree/fix/489-improve-keyboard-handling fix on snack. If something has already been resolved by the fix, please let me know.
Also, alpha 13 has a bug https://github.com/gorhom/react-native-bottom-sheet/issues/507 that needs to be resolved.

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 4.0.0-alpha.12   |

#### Snap points are set on iOS but not Android
When clicking inside the TextInput, the BottomSheet expands. Check the console log and click inside the TextInput
- iOS: it updates the BS snap point.
- Android: not updating snap point.

Because `searchSheet` hasn't snapped to point 2, as it does on iOS, `resultsCarouselRef.current?.close();` never fires so the resultsCarousel sheet never closes.

Another consequence of the same issue:

Drag `searchSheet` to the middle snap point. `resultsCarousel` will hide. Now click inside the TextInput. `searchSheet` will expand but not update the snap point on Android. Then manually drag the sheet to the bottom. `resultsCarousel` will not restore because it doesn't know anything changed.

#### BottomSheet gets stuck

Click inside the TextInput, the BottomSheet will expand. Submit on the keyboard and SearchHandle will `setRunningSearch(true)`, which will kick off a useEffect on `App.tsx` that will collapse the BottomSheet.

Try to drag the BottomSheet up. It will snap back to the bottom. Again, because it never updated the snap points.

#### BottomSheet stops responding

Click inside the TextInput, the BottomSheet will expand. Submit on the keyboard and SearchHandle will `setRunningSearch(true)`, which will kick off a useEffect on `App.tsx` that will collapse the BottomSheet.

- Drag the Results BottomSheet down. Search BottomSheet will expand.
- Drag the Search BottomSheet down. Results BottomSheet will **not** expand as expected.

### Both Android and iOS

1. Drag down the `resultsCarousel` and before it closes, click inside the TextInput. Search BottomSheet will not expand to the top as expected.
2. Drag down `resultsCarousel`. Search BottomSheet will start expanding. While it's expanding, drag it down. `resultsCarousel` will not expand as expected

## Reproducible sample code

https://snack.expo.io/@kickbk/android-keyboard-handling

**Comment by moyolvera** [comment] 2021-06-26 05:01
I have an issue related to keyboard, it is fine if post it in this thread?

Basically what happens is that the bottom sheet is visible for a few moments every time the keyboard is closed. If needed i can open another issue for this. But since is related to android and the keyboard i thought that this thread might be a good place to say it

**Comment by tlow92** [comment] 2021-06-28 13:33
@moyolvera Have the same issue, but it's not only for a few moments. It opens, when I hide the keyboard and it stays open as long as I don't close it. Maybe your code causes another rerender or something similar which closes the bottomsheet again after some time?

Nonetheless I have not found any workaround to prevent the bottomsheet from opening.

**Comment by moyolvera** [comment] 2021-06-28 14:47
@tlow92 i have this reproducible sample code on snack, it looks like what you are seeing?
Anyway i'm still not sure if i should open another issue, in the meantime i will leave it in here

https://snack.expo.io/@moyolvera/bottomsheet-bug-with-keyboard

**Comment by gorhom** [comment] 2021-06-29 20:28
@kickbk @tlow92 @moyolvera could you guys test alpha 17, thanks

```bash
yarn add @gorhom/bottom-sheet@4.0.0-alpha.17
```

**Comment by tlow92** [comment] 2021-06-29 21:38
@gorhom Can the fix be pulled into v2? Unfortunately I still have to use reanimated 1.x, so I'm unable to test with v4

**Comment by moyolvera** [comment] 2021-06-29 21:50
@gorhom issue is still present on alpha 17

https://snack.expo.io/@moyolvera/bottomsheet-bug-with-keyboard

**Comment by gorhom** [comment] 2021-07-01 21:03
@kickbk  @moyolvera could you guys test alpha 18 thanks 👏

```
yarn add @gorhom/bottom-sheet@4.0.0-alpha.18
```

**Comment by gorhom** [comment] 2021-07-01 21:04
>@gorhom Can the fix be pulled into v2? Unfortunately I still have to use reanimated 1.x, so I'm unable to test with v4

@tlow92 unfortunately, i am so busy these days with getting `v4` out, once im done it i'll look for improvements  for `v2`

**Comment by moyolvera** [comment] 2021-07-01 21:25
@gorhom thank you for all your work sir!. Unfortunately the issue i was describing still exists after updating to alpha 18. Here's a video of the issue:

https://user-images.githubusercontent.com/29616107/124191044-cde9ef80-da88-11eb-8b04-f43b9df2d464.mov

You can check the implementation on the snack link i shared above

**Comment by kickbk** [comment] 2021-07-01 21:28
@moyolvera your snack is using alpha 12 so it's not possible to check your issue with alpha 18. Please update and save your snack.

**Comment by moyolvera** [comment] 2021-07-01 21:30
@kickbk can you check again? i did forgot to click on the save button

**Comment by kickbk** [comment] 2021-07-01 21:43
@gorhom sorry, but no, the issues still exist. I saved the snack with alpha 18. You can test and follow the points to see the issues are not resolved.

**Comment by kickbk** [comment] 2021-07-01 22:07
@moyolvera nice catch. Indeed I can reproduce. I am guessing that the Bottom sheet is somehow attached in position to the android keyboard and closes with it. Only, perhaps it is slower than the actual Keyboard. Perhaps there's a way to distinguish whether that Keyboard was triggered via a `BottomSheetTextInput` vs a regular one, so it never matches the keyboard position in the latter case? I am totally guessing here.

**Comment by gorhom** [comment] 2021-07-03 12:01
could you guys create a reproducible sample code base on this template https://snack.expo.io/@gorhom/bottom-sheet-v4-reproducible-issue-template

**Comment by moyolvera** [comment] 2021-07-03 14:37
https://snack.expo.io/@moyolvera/bottomsheet-bug-with-keyboard

I can reproduce the issue even after using the template you provided, i just added backdrop to close the bottom sheet and a TextInput outside of the bottom sheet.

**Comment by gorhom** [comment] 2021-07-03 20:38
@moyolvera could you explain your expected behaviour ?

**Comment by moyolvera** [comment] 2021-07-03 20:42
@gorhom i would expect the bottomsheet not to behave like that. every time after closing the keyboard, the bottomsheet opens and closes for a moment, it's more visible when having a backdrop component, like the one i have in the snack. you can see a screen recording of the current behavior on a previous comment

**Comment by kickbk** [comment] 2021-07-04 01:06
@gorhom, here is the new snack based on yours: https://snack.expo.io/@kickbk/bk-bottom-sheet-v4-reproducible-issue-template. Here I go over my points above again. Very little has changed.

### Android Specific

**Repeat this process TWICE:**

Click inside the search field
Click on the "Filters" button to the right of the search field.
On iOS - works as expected
on Android - Shows filters, then closes it and shows the other two BottomSheet.

#### Snap points are set on iOS but not Android

Drag `searchSheet` to the middle snap point. `resultsCarousel` will hide. Now click inside the TextInput. `searchSheet` will expand but not update the snap point on Android. Then manually drag the sheet to the bottom. `resultsCarousel` will not restore because it doesn't know anything changed.

#### BottomSheet gets stuck

~~Click inside the TextInput, the BottomSheet will expand. Submit on the keyboard and SearchHandle will `setRunningSearch(true)`, which will kick off a useEffect on `App.tsx` that will collapse the BottomSheet.
Try to drag the BottomSheet up. It will snap back to the bottom. Again, because it never updated the snap points.~~
Seems to be resolved. I guess it was not related to snap points getting updated.

#### BottomSheet stops responding

Click inside the TextInput, the BottomSheet will expand. Submit on the keyboard and SearchHandle will `setRunningSearch(true)`, which will kick off a useEffect on `App.tsx` that will collapse the BottomSheet.

- Drag the Results BottomSheet down. Search BottomSheet will expand.
- Drag the Search BottomSheet down. Results BottomSheet will **not** expand as expected.

### Both Android and iOS

1. Drag down the `resultsCarousel` and before it closes, click inside the TextInput. Search BottomSheet will not expand to the top as expected.
2. Drag down `resultsCarousel`. Search BottomSheet will start expanding. While it's expanding, drag it down. `resultsCarousel` will not expand as expected

**Comment by gorhom** [comment] 2021-07-04 14:02
@moyolvera could you test `4.0.0-alpha.19`, it should stabilise the animated index 👍

**Comment by gorhom** [comment] 2021-07-04 16:38
@kickbk i have tested the first scenario and it works fine on android 


https://user-images.githubusercontent.com/4061838/124392636-ad22d380-dcee-11eb-9c9b-d0fd5f69984c.mov

**Comment by kickbk** [comment] 2021-07-04 17:43
@gorhom true that it's not consistent, however, here is what I mean (using the snack android simulator):
![mo1](https://user-images.githubusercontent.com/31323376/124394501-96f82180-dcb4-11eb-932c-9e251e170d69.gif)

**Comment by shensven** [comment] 2021-08-04 11:50
> @gorhom thank you for all your work sir!. Unfortunately the issue i was describing still exists after updating to alpha 18. Here's a video of the issue:
> 
>  Screen.Recording.2021-07-01.at.16.21.19.mov 
> You can check the implementation on the snack link i shared above

I have same problem

**Comment by megantaylor** [comment] 2021-08-20 14:39
hello! i've been very excited for all the improvements in v4 and am looking forward to being able to use it in my app in production, but i'm currently experiencing an issue (that i dont think has been described here) with the android keyboard / bottomsheet interaction.

i'm on expo 42, with android:windowSoftInputMode="adjustResize", using a bottomsheetscrollview in a bottomsheet. my scrollview has several inputs, and when i focus an input, the bottomsheet sort of expands past it snappoint as the keyboard opens and then moves back down to the correct snappoint. i see similar (but reversed) behavior when the keyboard is dismissed (video of behavior below).

is android keyboard support a feature i can count on moving forward?

https://user-images.githubusercontent.com/373062/130250378-4c4e9fdd-dcf5-47bd-987d-26694db8ce17.mp4

**Comment by gorhom** [comment] 2021-08-21 18:27
@megantaylor @shensven  please create a new issue and provide a reproducible sample snack

**Closed as completed by gorhom** 2021-08-21 18:27 UTC
Labels: bug

**Comment by gorhom** [comment] 2021-08-30 18:49
@all-contributors please add @kickbk for bug and test

**Comment by KingAmo** [comment] 2021-09-18 10:31
is it possible to disable keyboard handling ?
i think we should provide a props `enableKeyboardHandling`
@gorhom any help please?
