### ISSUE TITLE
Scrollables don't work

### ISSUE THREAD

**Issue by IleWdlI** [gorhom/react-native-bottom-sheet#550] opened 2021-07-22 14:24 UTC
# Bug

I'm currently using ^4.0.0-alpha.22 of the bottomSheet and I'm facing the following issue: My project is using react-navigation inside of the bottomSheet, and after launching and expanding, the sheet SectionList seems not to be working. But after navigation to another tab, which also consists of SectionList, scrolling starts working.
## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | ^4.0.0-alpha.22  |
| react-native                    | 0.64.0   |
| react-native-reanimated         | ^2.2.0   |
| react-native-gesture-handler    | ^1.10.3   |

## Steps To Reproduce

1. Nesting NavigationContainer of bottom-tabs and stacks to BottomSheet 
2. Using BottomSheetSectionList
3. Trying to scroll the list

Describe what you expected to happen:

1. Scrollable to work

**Comment by gorhom** [comment] 2021-07-22 14:36
provide a reproducible sample code on this template https://snack.expo.io/@gorhom/bottom-sheet-v4-reproducible-issue-template

**Comment by IleWdlI** [comment] 2021-07-23 09:24
Thank you for the fast response!

 Quick reproduction looks kind of like this:
 https://snack.expo.dev/@ilewdli/bottom-sheet-v4-reproducible-issue-template

I didn't use navigation, cause I hope this still serves the goal.

**Comment by nornewman** [comment] 2021-07-24 10:19
@gorhom thanks for the library! It's a life saver.

We're working on a project with pretty complex navigation (4 tabs, with different levels of page stacks inside, filled with scroll views, section lists, etc.) 

We've tried the alpha version, as on the stable one we've had issues with bottom inset of sheet being set in wrong position due to Android navbar element changes (on some Samsung phones it can be a line, (like on iPhone) or changed to usual 3 button setup) which caused the 0 position offset be calculated in the wrong way. Second issue was that on state updates, the sheet would close automatically.

And it's all fixed on Alpha, working perfectly for us, so again, thank you for it!

The only issue we have now, is that some lists are not scrollable on first focus :( 

We would really appreciate your help on it!

**Comment by gorhom** [comment] 2021-07-26 19:41
@IleWdlI remove the height from the `sections` style and it should be fine!

**Closed as completed by gorhom** 2021-07-26 19:41 UTC
Labels: bug

**Comment by IleWdlI** [comment] 2021-07-27 08:07
Thank you for the quick answer, but it appears that problem was related not in styles that you mentioned, but in wrapping SectionList with BottomSheetView. That was interesting, as we though that with that component it should only work better. Thanks so much for the help and quick responses!
