### ISSUE TITLE
[v4.0.0-alpha.27] When press on background bottom sheet becomes unresponsive

### ISSUE THREAD

**Issue by likern** [gorhom/react-native-bottom-sheet#578] opened 2021-08-15 22:00 UTC
# Bug

https://user-images.githubusercontent.com/842306/129493938-d48a0c8c-b770-4b36-925f-dc5bd52ee866.mp4

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | v4.0.0-alpha.27   |
| react-native                    | 0.64.0   |
| react-native-reanimated         |  2.3.0-alpha.2  |
| react-native-gesture-handler    | 1.10.3   |

## Steps To Reproduce

1. Open bottom sheet (with `[-1, "CONTENT_HEIGHT"]`) snap points
2. Close it by pressing on backdrop component
3. Bottom sheet becomes unresponsive 

Describe what you expected to happen:

1. Bottom sheet should be responsive and I able to press buttons again

**Comment by likern** [comment] 2021-08-15 22:20
@gorhom I've made some investigation and this is what I've found.

`onLayout` of `BottomSheetContainer` shows this **height** and it's the value of `animatedClosedPosition.value`
```bash
[BottomSheetContainer::handleContainerLayout] height:768.727294921875
```
while dynamic animated snap points are somehow shifted **by 1 pixel**:
```bash
[BottomSheet::useAnimatedReaction::OnMount] nextPosition:769.727294921875 animatedSnapPoints:769.727294921875,390.1818542480469 isLayoutCalculated:true
```

When pressing on backdrop there is position **768.727294921875**
```
[BottomSheet::handleClose] 
[BottomSheet::animateToPosition] velocity:0 position:768.727294921875 currentPosition:390.1818542480469
```
this leads to `[BottomSheet::useAnimatedReaction::OnChange] ...` not being called and this line is not executed
https://github.com/gorhom/react-native-bottom-sheet/blob/b65ea0df0de2bd0e6fca35a96a7ed2b4c2d81cb5/src/components/bottomSheet/BottomSheet.tsx#L1408 

I think this is the reason.

It's not being called because the last `_animatedIndex.value` is `0.02` and this condition is `true`

https://github.com/gorhom/react-native-bottom-sheet/blob/b65ea0df0de2bd0e6fca35a96a7ed2b4c2d81cb5/src/components/bottomSheet/BottomSheet.tsx#L1375-L1377

**Comment by likern** [comment] 2021-08-15 22:22
```bash
 LOG  2021-08-15T22:02:58.151Z | DEBUG | ContentBottomSheet] screenWidth [392.72727272727275], screenHeight [850.9090909090909], windowWidth [392.72727272727275], windowHeight [803.6363636363636]
 LOG  animatedSnapPoints: {"value":[-999]}
 LOG  animatedHandleHeight: -999
 LOG  animatedContentHeight: 0
 LOG  [BottomSheet::render] animatedSnapPoints:-999 animatedCurrentIndex:-1 providedIndex:0
 LOG  2021-08-15T22:02:58.751Z | DEBUG | [TaskSettings] render id [5f7fd19c-21e1-48af-8925-124928adfebd]
 LOG  2021-08-15T22:02:58.752Z | DEBUG | [TaskSettings] task is [{"id":"5f7fd19c-21e1-48af-8925-124928adfebd","author":"Q3mwjQWQxTRm06L11YeALBaW2Fg2","title":"One","createdAt":"2021-08-15T21:25:14.901Z","completedAt":null,"isArchived":false,"isCompleted":false,"isTracked":false,"trackedSeconds":0,"tags":[],"subtasks":[]}]
 LOG  2021-08-15T22:02:58.752Z | DEBUG | [TaskSettings] before render
 LOG  2021-08-15T22:02:58.757Z | DEBUG | [Task] render task with id [5f7fd19c-21e1-48af-8925-124928adfebd]
 LOG  2021-08-15T22:02:58.763Z | DEBUG | RemindMePanel: run
 LOG  2021-08-15T22:02:58.769Z | DEBUG | ContentBottomSheet] screenWidth [392.72727272727275], screenHeight [850.9090909090909], windowWidth [392.72727272727275], windowHeight [803.6363636363636]
 LOG  animatedSnapPoints: {"value":[-999]}
 LOG  animatedHandleHeight: -999
 LOG  animatedContentHeight: 0
 LOG  [BottomSheet::render] animatedSnapPoints:-999 animatedCurrentIndex:-1 providedIndex:0
 LOG  2021-08-15T22:02:58.858Z | DEBUG | [TaskSettings]: setTaskTagsAtomFamily called
 LOG  onLayout: {"target":1595,"layout":{"width":392.7272644042969,"y":0,"height":354.5454406738281,"x":0}}
 LOG  [BottomSheetHandleContainer::handleContainerLayout] height:24
 LOG  [BottomSheetContainer::handleContainerLayout] height:768.727294921875
 LOG  [BottomSheet::useAnimatedReaction::OnMount] nextPosition:769.727294921875 animatedSnapPoints:769.727294921875,390.1818542480469 isLayoutCalculated:true
 LOG  [BottomSheet::animateToPosition] velocity:0 position:769.727294921875 currentPosition:803.6363636363636
 LOG  [BottomSheet::handleOnAnimate] toIndex:0 fromIndex:-1
 LOG  [BottomSheet::animateToPositionCompleted] animatedNextPositionIndex:0 animatedNextPosition:769.727294921875 animatedCurrentIndex:-1
 LOG  [BottomSheet::useAnimatedReaction::OnChange] animatedIndex:0 animatedCurrentIndex:-1
 LOG  [BottomSheet::handleOnChange] index:0 animatedCurrentIndex:0
 LOG  onAddReminderPress: pressed!
 LOG  bottom sheet: open is called
 LOG  [BottomSheet::handleExpand] 
 LOG  [BottomSheet::animateToPosition] velocity:0 position:390.1818542480469 currentPosition:769.727294921875
 LOG  [BottomSheet::handleOnAnimate] toIndex:1 fromIndex:0
 LOG  [BottomSheet::animateToPositionCompleted] animatedNextPositionIndex:1 animatedNextPosition:390.1818542480469 animatedCurrentIndex:0
 LOG  [BottomSheet::useAnimatedReaction::OnChange] animatedIndex:1 animatedCurrentIndex:0
 LOG  [BottomSheet::handleOnChange] index:1 animatedCurrentIndex:1
 LOG  [BottomSheet::handleClose] 
 LOG  [BottomSheet::animateToPosition] velocity:0 position:768.727294921875 currentPosition:390.1818542480469
 LOG  [BottomSheet::handleOnAnimate] toIndex:-1 fromIndex:1
 LOG  [BottomSheet::animateToPositionCompleted] animatedNextPositionIndex:-1 animatedNextPosition:768.727294921875 animatedCurrentIndex:1
```

**Comment by gorhom** [comment] 2021-08-16 19:52
@likern thanks for submitting this issue, could you provide a link to a reproducible snack ?

**Comment by likern** [comment] 2021-08-16 19:58
I haven't yet. But this is mainly this code.  

```
const initialSnapPoints = useMemoOne(() => {
    return [-1, 'CONTENT_HEIGHT'];
}, []);
...
const {
      animatedHandleHeight,
      animatedSnapPoints,
      animatedContentHeight,
      handleContentLayout
} = useBottomSheetDynamicSnapPoints(initialSnapPoints);
...
<BottomSheet
          ref={reactNativeBottomSheetRef}
          snapPoints={animatedSnapPoints}
          handleComponent={Handle}
          backdropComponent={BottomSheetBackdrop}
          handleHeight={animatedHandleHeight}
          contentHeight={animatedContentHeight}
          enablePanDownToClose={true}
          enableOverDrag={false}
        >
          <BottomSheetView
            style={{ backgroundColor: 'red' }}
            onLayout={event => {
              console.log(`onLayout: ${JSON.stringify(event.nativeEvent)}`);
              handleContentLayout(event);
            }}
          >
            {children}
          </BottomSheetView>
</BottomSheet>
```

**Comment by likern** [comment] 2021-08-16 19:59
I've figured out the cause of the bug.

I have used snap points as in example in documentation: `snapPoints={[-1, '100%']}`.
From this context It's expected that `-1` value **is allowed in snap points array**.

But this code expects `normalizedSnapPoint` is always non-negative. For `-1` this becomes
`containerHeight - normalizedSnapPoint = 768.727294921875 - (-1) = 769.727294921875`.

https://github.com/gorhom/react-native-bottom-sheet/blob/b65ea0df0de2bd0e6fca35a96a7ed2b4c2d81cb5/src/utilities/normalizeSnapPoint.ts#L19

**Comment by gorhom** [comment] 2021-08-16 20:13
aha, i should prevent the `-1` from `snapPoints`, since i introduce `enablePanDownToClose` prop! good catch 👏

**Comment by likern** [comment] 2021-08-16 20:18
> @likern thanks for submitting this issue, could you provide a link to a reproducible snack ?

https://snack.expo.dev/@victormalov/bottom-sheet-v4-reproducible-issue-template

**Comment by likern** [comment] 2021-08-16 20:24
> aha, i should prevent the `-1` from `snapPoints`, since i introduce `enablePanDownToClose` prop! good catch

Should we prevent **all negative values** (except somehow handle `[-999] case)`? Since they also break the logic the same way and `enablePanDownToClose` already provides minimal full offset.

**Comment by likern** [comment] 2021-08-16 20:28
> > aha, i should prevent the `-1` from `snapPoints`, since i introduce `enablePanDownToClose` prop! good catch
> 
> Should we prevent **all negative values** (except somehow handle `[-999] case)`? Since they also break the logic the same way and `enablePanDownToClose` already provides minimal full offset.

If we expect `Symbol` is supported, we can substitute special `[-999]` with custom internal `Symbol`, which could be obtained only from `useBottomSheetDynamicSnapPoints` and abandon completely any negative values.

**Comment by gorhom** [comment] 2021-08-17 21:25
it should be resolved with https://github.com/gorhom/react-native-bottom-sheet/commit/95ea72a459f96d40ad583c5579cc72f0e128e5dd and released on the next alpha release 👍

**Closed as completed by gorhom** 2021-08-17 21:25 UTC
Labels: bug
