### ISSUE TITLE
Bottom-sheet raises warning in react-navigation with deep equal

### ISSUE THREAD

**Issue by mlecoq** [gorhom/react-native-bottom-sheet#297] opened 2021-02-18 22:22 UTC
# Bug

The original issue is here (with reproduction example)

https://github.com/react-navigation/react-navigation/issues/9330

I first thought that the issue was within react-navigation (where the warning came from) but it seems to be an issue in bottom sheet

What is strange is that everything works as expected (just a warning is displayed)

## Environment info

| Library                         | Version |
| ------------------------------- | ------- |
| @gorhom/bottom-sheet         | 3.3.1   |
| react-native                    | 6.3.4 |
| react-native-reanimated         | 2-rc.3   |

## Steps To Reproduce

1. Run the provided example
2. Go from tab 2.1 to tab 2.2 and go back to 2.1
3. A warning is displayed

Describe what you expected to happen:

1. No warning

## Reproducible sample code

https://github.com/mlecoq/materialTopTabBarIssue

In the example I put 2 top tab bar but in my original case I have one bottom and one top bar (and I want that bottom sheet appears above bottom tab) 

Previously I was using react-native-portalize + bottomsheet and I had the same warning 

As said here (https://github.com/react-navigation/react-navigation/issues/9330#issuecomment-781446731) bottom sheet makes a deep equal comparison of props, what for ? Could it be removed ?

**Comment by gorhom** [comment] 2021-02-19 12:21
@mlecoq thanks for submitting this issue, i will look into it later today 👍

**Comment by gorhom** [comment] 2021-03-02 22:41
@mlecoq i have looked at the issue and seems to be solved by extracting the screen into a component instead of providing it in the navigator it self:

```tsx
const Tab2Screen = () => {
  return (
    <View>
      <Text>Tab 2.2</Text>
      <BottomSheetModal snapPoints={snapPoints}>
        <Text>Modal</Text>
      </BottomSheetModal>
    </View>
  );
};
```

the reason why i use deep equal comparison in bottom sheet is to prevent unwanted renderings that causes glitches in animation/interaction.

please let me know if the solution did fix your issue, thanks 👍

**Comment by mlecoq** [comment] 2021-03-03 09:15
Hi @gorhom 

I reproduce the issue in this case 

```
const Tab2Screen = () => (
  <View>
    <Text>Tab 2.2</Text>
    <BottomSheetModal
      waitFor={[]}
      simultaneousHandlers={[]}
      snapPoints={snapPoints}
    >
      <Text>Modal</Text>
    </BottomSheetModal>
  </View>
);

export default function App() {
  return (
    <NavigationContainer>
      <BottomSheetModalProvider>
        <Tab1.Navigator initialRouteName="Tab 1">
          <Tab1.Screen name="Tab 1">{() => <Text>Tab 1</Text>}</Tab1.Screen>
          <Tab1.Screen name="Tab2">
            {() => (
              <Tab2.Navigator initialRouteName="Tab 2.1">
                <Tab2.Screen name="Tab 2.1">
                  {() => <Text>Tab 2.1</Text>}
                </Tab2.Screen>

                <Tab2.Screen name="Tab 2.2">{() => <Tab2Screen />}</Tab2.Screen>
              </Tab2.Navigator>
            )}
          </Tab1.Screen>
        </Tab1.Navigator>
      </BottomSheetModalProvider>
    </NavigationContainer>
  );
}
```

But not in if I put the component directly 
```
<Tab2.Screen name="Tab 2.2" component={Tab2Screen} />
```

Unfortunately in the app I am developing I need to use the pattern 
```<Tab2.Screen name="Tab 2.2">{() => <Tab2Screen />}</Tab2.Screen>```

to pass additional parameters in components (these parameters cannot be passed by route params).

In fact I have dynamic tabs 

```
<TopTabBar initialRouteName="reports">
          {tabs.map((tab) => (
              <Tab.Screen key={tab.id} name={tab.name} options={{title: t(tab.name)}}>
                {() => <ReportsList  tab={tab} />}
              </Tab.Screen>
            ))
          )}
</TopTabBar>
```

**Comment by gorhom** [comment] 2021-03-03 17:11
hmm why not pass the `tab` object as an initial parameter instead a prop ?

```tsx
<TopTabBar initialRouteName="reports">
  {tabs.map((tab) => (
    <Tab.Screen
      key={tab.id}
      name={tab.name}
      options={{title: t(tab.name)}}
      initialParams={{ tab }}
      component={ReportsList}
    />
  )))}
</TopTabBar>
```

**Comment by mlecoq** [comment] 2021-03-03 19:42
I was wondering why I did not code what you suggest so I try it and I have another warning from react-navigation

 `WARN     Non-serializable values were found in the navigation state. Check: ... `

In fact in tabs I have observables (from `watermelondb`) - I could make it different (passing id of object instead of full object) but it has annoying side effects

**Comment by kickbk** [comment] 2021-03-19 22:19
@gorhom I'm also getting this issue with v2. In my case, I believe I do pass the screen as a component to the Stack Navigator. 

Let me copy [what I posted on StackOverflow](https://stackoverflow.com/questions/66713853/usefocuseffect-with-useeffect-randomly-returns-warning-property-of-the-route) which Satya caught and referenced:
I have a `useFocusEffect` which sets a state when leaving the `Search` screen - `setAlert` is set to null, which then fires a function that closes a bottom sheet (alerts).
```
useFocusEffect(
  React.useCallback(() => {
    return () => {
      setAlert(null);
    };
  }, [setAlert])
```
I **randomly** get this warning when moving to another screen** while the alerts bottom sheet is open**: `Accessing the 'state' property of the 'route' object is not supported. If you want to get the focused route name, use the 'getFocusedRouteNameFromRoute' helper instead: https://reactnavigation.org/docs/screen-options-resolution/#setting-parent-screen-options-based-on-child-navigators-state`

When I disable this `useFocusEffect`, the warning goes away.

To give more context, this is my stack navigator:

```
import SearchScreen from '../screens/search/SearchScreen';
function SearchNavigator() {
  const SearchStack = createStackNavigator<ClientSearchStackParamList>();
  return (
    <SearchStack.Navigator>
      <SearchStack.Screen name="Search" component={SearchScreen} options={{ headerShown: false }} />
     ...
    </SearchStack.Navigator>
  );
}
```

And my SearchScreen is a function:
```
const SearchScreen = () => {
  ...
  useFocusEffect(
    React.useCallback(() => {
      return () => {
        setAlert(null);
        searchModalRef.current?.collapse();
        filtersModalRef.current?.dismiss();
      };
    }, [setAlert])
  );
  return (
    <BottomSheetModalProvider>
      ...
      <Alerts ref={alertsModalRef} />
```

`<Alerts>` is a component I import:
```
const Alerts = forwardRef((ref: React.ForwardedRef<BottomSheetModal> | null) => {
  return (
        <BottomSheetModal
          ref={ref}
          name="AlertsModal"
          index={1}
          snapPoints={alertModalSnapPoints}
          topInset={topSafeArea}
          animatedPosition={animatedModalPosition}
          handleComponent={Handle}
          onDismiss={() => {
            setAlert(null);
          }}>
          {display(alert)}
        </BottomSheetModal>
      );
   ...
```

**Comment by nicgutierrez** [comment] 2021-03-20 21:53
Hey @gorhom , same issue for me with react navigation! Although my use case is slightly different. I have a "global" bottom sheet that I want to display when a specific item on the tab bar is clicked.  My tabs are inside a stack navigator. 

I added the bottom sheet at the same level of my tabs, within a Fragment and I get the error above about accessing state. Something like this:

```
<Fragment>
    <Tab.Navigator>
        ...
    </Tab.Navigator>
    <BottomSheet ... />
</Fragment>
```

Do you have any suggestions on how to achieve a "global" bottom sheet that should be triggered when a tab button is clicked? thanks

**Comment by LadislavBohm** [comment] 2021-04-04 21:31
Like others have said it also happens on v2. My use case was to share one bottom sheet across multiple bottom tabs. What I thought would work great is to place bottom sheet component together with <BottomTabBar /> component in navigator but then this issue happens.

What I in the end did was to place the sheet on each screen, keep ref to each screen by it's route name and refer to it from top component to handle shared code for opening/closing it when moving between tabs.

**Comment by gorhom** [comment] 2021-04-07 19:56
hey everyone, quick update, i will investigate removing deep equal checking and see it's side effect 👍

**Comment by gorhom** [comment] 2021-04-10 16:39
@mlecoq @kickbk would you mind testing #395 for `v3` :)

soon i will push this update for `v2` 👍

**Comment by mlecoq** [comment] 2021-04-10 18:06
Sure I will test it on Monday, thanks a lot !

**Comment by kickbk** [comment] 2021-04-10 19:49
Will do ASAP

**Comment by mlecoq** [comment] 2021-04-12 08:29
@gorhom on my app It works fine, the warning is no more raised. Thanks a lot !

**Comment by nicgutierrez** [comment] 2021-04-16 08:54
@gorhom is this fix already released for v3?

**Comment by kickbk** [comment] 2021-04-23 23:44
@gorhom Sorry it took so long for me to get to testing this fix. I can confirm the warning is gone 👍

**Comment by gorhom** [comment] 2021-04-24 12:47
thanks everyone for your help, this should be resolved with `v3.6.4` 👍

**Closed as completed by gorhom** 2021-04-24 12:47 UTC
Labels: bug, v3

**Comment by LadislavBohm** [comment] 2021-04-24 16:49
Is there any chance to get this fix in v2 as well? It would be awesome as I can't switch to v3 since react navigation does not support it yet.

**Comment by kickbk** [comment] 2021-04-24 17:33
> Is there any chance to get this fix in v2 as well? It would be awesome as I can't switch to v3 since react navigation does not support it yet.

React navigation supports it just fine. Are you using expo? If so, upgrade to SDK 41.
